name: On Issue Created

on:
  issues:
    types: [opened]

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:   
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This fetches all history

    - name: Update file
      run: |
        echo "Issue #$GITHUB_EVENT_NUMBER by $GITHUB_ACTOR: $GITHUB_EVENT_TITLE" >> issues.txt
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.issue.number }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_EVENT_TITLE: ${{ github.event.issue.title }}

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add issues.txt
        git commit -m "Update issues.txt with new issue #$GITHUB_EVENT_NUMBER"
        git status
        git push https://<robertgarrigos>:${{ secrets.ONA_CODINENCA_TWEETS }}@github.com/Ona-Codinenca/Entrades_twitter.git HEAD:$(git rev-parse --abbrev-ref HEAD)

      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.issue.number }}
